apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
      id: 1
  template:
    metadata:
      labels:
        app: controller
        id: 1
    spec:
      containers:
        - name: controller-1
          image: apache/kafka:latest
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "controller"
            - name: KAFKA_LISTENERS
              value: "CONTROLLER://:9093"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@controller-1:9093,2@controller-2:9093,3@controller-3:9093"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
          ports:
            - containerPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
      id: 2
  template:
    metadata:
      labels:
        app: controller
        id: 2
    spec:
      containers:
        - name: controller-2
          image: apache/kafka:latest
          env:
            - name: KAFKA_NODE_ID
              value: "2"
            - name: KAFKA_PROCESS_ROLES
              value: "controller"
            - name: KAFKA_LISTENERS
              value: "CONTROLLER://:9093"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@controller-1:9093,2@controller-2:9093,3@controller-3:9093"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
          ports:
            - containerPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
      id: 3
  template:
    metadata:
      labels:
        app: controller
        id: 3
    spec:
      containers:
        - name: controller-3
          image: apache/kafka:latest
          env:
            - name: KAFKA_NODE_ID
              value: "3"
            - name: KAFKA_PROCESS_ROLES
              value: "controller"
            - name: KAFKA_LISTENERS
              value: "CONTROLLER://:9093"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@controller-1:9093,2@controller-2:9093,3@controller-3:9093"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
          ports:
            - containerPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
      id: 1
  template:
    metadata:
      labels:
        app: broker
        id: 1
    spec:
      containers:
        - name: broker-1
          image: apache/kafka:latest
          env:
            - name: KAFKA_NODE_ID
              value: "4"
            - name: KAFKA_PROCESS_ROLES
              value: "broker"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:19092,PLAINTEXT_HOST://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://broker-1:19092,PLAINTEXT_HOST://localhost:29092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@controller-1:9093,2@controller-2:9093,3@controller-3:9093"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
          ports:
            - containerPort: 19092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
      id: 2
  template:
    metadata:
      labels:
        app: broker
        id: 2
    spec:
      containers:
        - name: broker-2
          image: apache/kafka:latest
          env:
            - name: KAFKA_NODE_ID
              value: "5"
            - name: KAFKA_PROCESS_ROLES
              value: "broker"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:19092,PLAINTEXT_HOST://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://broker-2:19092,PLAINTEXT_HOST://localhost:39092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@controller-1:9093,2@controller-2:9093,3@controller-3:9093"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
          ports:
            - containerPort: 19092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
      id: 3
  template:
    metadata:
      labels:
        app: broker
        id: 3
    spec:
      containers:
        - name: broker-3
          image: apache/kafka:latest
          env:
            - name: KAFKA_NODE_ID
              value: "6"
            - name: KAFKA_PROCESS_ROLES
              value: "broker"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:19092,PLAINTEXT_HOST://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://broker-3:19092,PLAINTEXT_HOST://localhost:49092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@controller-1:9093,2@controller-2:9093,3@controller-3:9093"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
          ports:
            - containerPort: 19092
