#!/bin/bash

docker exec broker-1 /kafka/add-topic
docker exec broker-1 /kafka/add-events

sleep 2

docker exec broker-1 /kafka/read-events
docker exec broker-2 /kafka/read-events
docker exec broker-3 /kafka/read-events
