#!/bin/bash

echo HELLO FROM NODE $KAFKA_NODE_ID

/opt/kafka/bin/kafka-console-consumer.sh \
       --bootstrap-server broker-1:19092,broker-2:19092,broker-3:19092 \
       --topic seismic-data \
       --from-beginning \
       --max-messages 2
